// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as GetLoginAccountProcedure from "../get_login_account_procedure";
import * as GetPlayerSnapshotProcedure from "../get_player_snapshot_procedure";
import * as GetPlayerSnapshotBySaveKeyProcedure from "../get_player_snapshot_by_save_key_procedure";
import * as GetWorldCharacterProcedure from "../get_world_character_procedure";
import * as GetWorldCharacterBySaveKeyProcedure from "../get_world_character_by_save_key_procedure";
import * as ListLoginAccountsProcedure from "../list_login_accounts_procedure";
import * as ListPlayerSnapshotsForWorldProcedure from "../list_player_snapshots_for_world_procedure";
import * as ListWorldCharactersForWorldProcedure from "../list_world_characters_for_world_procedure";

export type GetLoginAccountArgs = __Infer<typeof GetLoginAccountProcedure.params>;
export type GetLoginAccountResult = __Infer<typeof GetLoginAccountProcedure.returnType>;
export type GetPlayerSnapshotArgs = __Infer<typeof GetPlayerSnapshotProcedure.params>;
export type GetPlayerSnapshotResult = __Infer<typeof GetPlayerSnapshotProcedure.returnType>;
export type GetPlayerSnapshotBySaveKeyArgs = __Infer<typeof GetPlayerSnapshotBySaveKeyProcedure.params>;
export type GetPlayerSnapshotBySaveKeyResult = __Infer<typeof GetPlayerSnapshotBySaveKeyProcedure.returnType>;
export type GetWorldCharacterArgs = __Infer<typeof GetWorldCharacterProcedure.params>;
export type GetWorldCharacterResult = __Infer<typeof GetWorldCharacterProcedure.returnType>;
export type GetWorldCharacterBySaveKeyArgs = __Infer<typeof GetWorldCharacterBySaveKeyProcedure.params>;
export type GetWorldCharacterBySaveKeyResult = __Infer<typeof GetWorldCharacterBySaveKeyProcedure.returnType>;
export type ListLoginAccountsArgs = __Infer<typeof ListLoginAccountsProcedure.params>;
export type ListLoginAccountsResult = __Infer<typeof ListLoginAccountsProcedure.returnType>;
export type ListPlayerSnapshotsForWorldArgs = __Infer<typeof ListPlayerSnapshotsForWorldProcedure.params>;
export type ListPlayerSnapshotsForWorldResult = __Infer<typeof ListPlayerSnapshotsForWorldProcedure.returnType>;
export type ListWorldCharactersForWorldArgs = __Infer<typeof ListWorldCharactersForWorldProcedure.params>;
export type ListWorldCharactersForWorldResult = __Infer<typeof ListWorldCharactersForWorldProcedure.returnType>;

