// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AppendLiveEventReducer from "../append_live_event_reducer";
import DrainScheduledJobReducer from "../drain_scheduled_job_reducer";
import EnqueueScheduledJobReducer from "../enqueue_scheduled_job_reducer";
import PublishWorldReleaseReducer from "../publish_world_release_reducer";
import PutAgentMemoryReducer from "../put_agent_memory_reducer";
import PutAgentProfileReducer from "../put_agent_profile_reducer";
import PutPlayerSnapshotReducer from "../put_player_snapshot_reducer";
import PutPrefabReducer from "../put_prefab_reducer";
import PutTrajectoryEpisodeReducer from "../put_trajectory_episode_reducer";
import PutTrajectoryStepReducer from "../put_trajectory_step_reducer";
import PutWorldPatchReducer from "../put_world_patch_reducer";
import RegisterWorldPackageReducer from "../register_world_package_reducer";
import TouchLoginAccountReducer from "../touch_login_account_reducer";
import TouchWorldCharacterReducer from "../touch_world_character_reducer";
import UpsertLoginAccountReducer from "../upsert_login_account_reducer";
import UpsertPrincipalReducer from "../upsert_principal_reducer";
import UpsertWorldReducer from "../upsert_world_reducer";
import UpsertWorldCharacterReducer from "../upsert_world_character_reducer";

export type AppendLiveEventParams = __Infer<typeof AppendLiveEventReducer>;
export type DrainScheduledJobParams = __Infer<typeof DrainScheduledJobReducer>;
export type EnqueueScheduledJobParams = __Infer<typeof EnqueueScheduledJobReducer>;
export type PublishWorldReleaseParams = __Infer<typeof PublishWorldReleaseReducer>;
export type PutAgentMemoryParams = __Infer<typeof PutAgentMemoryReducer>;
export type PutAgentProfileParams = __Infer<typeof PutAgentProfileReducer>;
export type PutPlayerSnapshotParams = __Infer<typeof PutPlayerSnapshotReducer>;
export type PutPrefabParams = __Infer<typeof PutPrefabReducer>;
export type PutTrajectoryEpisodeParams = __Infer<typeof PutTrajectoryEpisodeReducer>;
export type PutTrajectoryStepParams = __Infer<typeof PutTrajectoryStepReducer>;
export type PutWorldPatchParams = __Infer<typeof PutWorldPatchReducer>;
export type RegisterWorldPackageParams = __Infer<typeof RegisterWorldPackageReducer>;
export type TouchLoginAccountParams = __Infer<typeof TouchLoginAccountReducer>;
export type TouchWorldCharacterParams = __Infer<typeof TouchWorldCharacterReducer>;
export type UpsertLoginAccountParams = __Infer<typeof UpsertLoginAccountReducer>;
export type UpsertPrincipalParams = __Infer<typeof UpsertPrincipalReducer>;
export type UpsertWorldParams = __Infer<typeof UpsertWorldReducer>;
export type UpsertWorldCharacterParams = __Infer<typeof UpsertWorldCharacterReducer>;

