// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  principalId: __t.string().primaryKey().name("principal_id"),
  agentId: __t.string().name("agent_id"),
  displayName: __t.string().name("display_name"),
  personaJson: __t.option(__t.string()).name("persona_json"),
  controllerDefaultsJson: __t.option(__t.string()).name("controller_defaults_json"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
