// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  memoryId: __t.string().primaryKey().name("memory_id"),
  principalId: __t.string().name("principal_id"),
  memoryScope: __t.string().name("memory_scope"),
  worldId: __t.option(__t.string()).name("world_id"),
  memoryKey: __t.string().name("memory_key"),
  valueJson: __t.string().name("value_json"),
  updatedAt: __t.u64().name("updated_at"),
});
