// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.string().name("event_id"),
  worldId: __t.option(__t.string()).name("world_id"),
  principalId: __t.option(__t.string()).name("principal_id"),
  worldCharacterId: __t.option(__t.string()).name("world_character_id"),
  eventKind: __t.string().name("event_kind"),
  payloadJson: __t.option(__t.string()).name("payload_json"),
  createdAt: __t.u64().name("created_at"),
});
