// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  username: __t.string().primaryKey(),
  principalId: __t.string().name("principal_id"),
  authMode: __t.string().name("auth_mode"),
  passwordHash: __t.option(__t.string()).name("password_hash"),
  passwordSalt: __t.option(__t.string()).name("password_salt"),
  passwordAlgorithm: __t.option(__t.string()).name("password_algorithm"),
  externalSubject: __t.option(__t.string()).name("external_subject"),
  banned: __t.bool(),
  banReason: __t.option(__t.string()).name("ban_reason"),
  createdAt: __t.u64().name("created_at"),
  lastLoginAt: __t.option(__t.u64()).name("last_login_at"),
});
