// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  releaseId: __t.string(),
  packageId: __t.string(),
  worldId: __t.string(),
  imageRef: __t.string(),
  revision: __t.string(),
  configJson: __t.string(),
  createdAt: __t.u64(),
  deployedAt: __t.option(__t.u64()),
};
