// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  prefabId: __t.string(),
  ownerPrincipalId: __t.string(),
  name: __t.string(),
  prefabKind: __t.string(),
  payloadJson: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
};
