// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  patchId: __t.string(),
  packageId: __t.option(__t.string()),
  worldId: __t.option(__t.string()),
  patchKind: __t.string(),
  payloadJson: __t.string(),
  createdAt: __t.u64(),
};
