// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  worldCharacterId: __t.string(),
  worldId: __t.string(),
  principalId: __t.string(),
  snapshotVersion: __t.u32(),
  persistentVarsJson: __t.string(),
  updatedAt: __t.u64(),
};
