// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AgentMemory = __t.object("AgentMemory", {
  memoryId: __t.string(),
  principalId: __t.string(),
  memoryScope: __t.string(),
  worldId: __t.option(__t.string()),
  memoryKey: __t.string(),
  valueJson: __t.string(),
  updatedAt: __t.u64(),
});
export type AgentMemory = __Infer<typeof AgentMemory>;

export const AgentProfile = __t.object("AgentProfile", {
  principalId: __t.string(),
  agentId: __t.string(),
  displayName: __t.string(),
  personaJson: __t.option(__t.string()),
  controllerDefaultsJson: __t.option(__t.string()),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type AgentProfile = __Infer<typeof AgentProfile>;

export const LiveEvent = __t.object("LiveEvent", {
  eventId: __t.string(),
  worldId: __t.option(__t.string()),
  principalId: __t.option(__t.string()),
  worldCharacterId: __t.option(__t.string()),
  eventKind: __t.string(),
  payloadJson: __t.option(__t.string()),
  createdAt: __t.u64(),
});
export type LiveEvent = __Infer<typeof LiveEvent>;

export const LoginAccount = __t.object("LoginAccount", {
  username: __t.string(),
  principalId: __t.string(),
  authMode: __t.string(),
  passwordHash: __t.option(__t.string()),
  passwordSalt: __t.option(__t.string()),
  passwordAlgorithm: __t.option(__t.string()),
  externalSubject: __t.option(__t.string()),
  banned: __t.bool(),
  banReason: __t.option(__t.string()),
  createdAt: __t.u64(),
  lastLoginAt: __t.option(__t.u64()),
});
export type LoginAccount = __Infer<typeof LoginAccount>;

export const LoginAccountRow = __t.object("LoginAccountRow", {
  username: __t.string(),
  principalId: __t.string(),
  authMode: __t.string(),
  passwordHash: __t.option(__t.string()),
  passwordSalt: __t.option(__t.string()),
  passwordAlgorithm: __t.option(__t.string()),
  externalSubject: __t.option(__t.string()),
  banned: __t.bool(),
  banReason: __t.option(__t.string()),
  createdAt: __t.u64(),
  lastLoginAt: __t.option(__t.u64()),
});
export type LoginAccountRow = __Infer<typeof LoginAccountRow>;

export const PlayerSnapshot = __t.object("PlayerSnapshot", {
  worldCharacterId: __t.string(),
  worldId: __t.string(),
  principalId: __t.string(),
  snapshotVersion: __t.u32(),
  persistentVarsJson: __t.string(),
  updatedAt: __t.u64(),
});
export type PlayerSnapshot = __Infer<typeof PlayerSnapshot>;

export const PlayerSnapshotRow = __t.object("PlayerSnapshotRow", {
  worldCharacterId: __t.string(),
  worldId: __t.string(),
  principalId: __t.string(),
  snapshotVersion: __t.u32(),
  persistentVarsJson: __t.string(),
  updatedAt: __t.u64(),
});
export type PlayerSnapshotRow = __Infer<typeof PlayerSnapshotRow>;

export const Prefab = __t.object("Prefab", {
  prefabId: __t.string(),
  ownerPrincipalId: __t.string(),
  name: __t.string(),
  prefabKind: __t.string(),
  payloadJson: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type Prefab = __Infer<typeof Prefab>;

export const Principal = __t.object("Principal", {
  principalId: __t.string(),
  principalKind: __t.string(),
  canonicalName: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type Principal = __Infer<typeof Principal>;

export const ScheduledJob = __t.object("ScheduledJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  jobId: __t.string(),
  worldId: __t.option(__t.string()),
  jobKind: __t.string(),
  payloadJson: __t.string(),
  createdAt: __t.u64(),
});
export type ScheduledJob = __Infer<typeof ScheduledJob>;

export const TrajectoryEpisode = __t.object("TrajectoryEpisode", {
  episodeId: __t.string(),
  worldId: __t.string(),
  principalId: __t.string(),
  worldCharacterId: __t.string(),
  source: __t.string(),
  model: __t.option(__t.string()),
  buildSha: __t.option(__t.string()),
  startedAt: __t.u64(),
  endedAt: __t.option(__t.u64()),
});
export type TrajectoryEpisode = __Infer<typeof TrajectoryEpisode>;

export const TrajectoryStep = __t.object("TrajectoryStep", {
  stepId: __t.string(),
  episodeId: __t.string(),
  stepIndex: __t.u32(),
  tick: __t.option(__t.u64()),
  observationToon: __t.option(__t.string()),
  actionKind: __t.option(__t.string()),
  actionToon: __t.option(__t.string()),
  outcomeToon: __t.option(__t.string()),
  latencyMs: __t.option(__t.u32()),
  rewardTagsJson: __t.option(__t.string()),
  createdAt: __t.u64(),
});
export type TrajectoryStep = __Infer<typeof TrajectoryStep>;

export const World = __t.object("World", {
  worldId: __t.string(),
  name: __t.string(),
  gamemodeId: __t.string(),
  status: __t.string(),
  releaseId: __t.option(__t.string()),
  ownerPrincipalId: __t.option(__t.string()),
  metadataJson: __t.option(__t.string()),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type World = __Infer<typeof World>;

export const WorldCharacter = __t.object("WorldCharacter", {
  worldCharacterId: __t.string(),
  worldId: __t.string(),
  principalId: __t.string(),
  displayName: __t.string(),
  saveKey: __t.option(__t.string()),
  branchKind: __t.option(__t.string()),
  createdAt: __t.u64(),
  lastSeenAt: __t.option(__t.u64()),
});
export type WorldCharacter = __Infer<typeof WorldCharacter>;

export const WorldCharacterRow = __t.object("WorldCharacterRow", {
  worldCharacterId: __t.string(),
  worldId: __t.string(),
  principalId: __t.string(),
  displayName: __t.string(),
  saveKey: __t.option(__t.string()),
  branchKind: __t.option(__t.string()),
  createdAt: __t.u64(),
  lastSeenAt: __t.option(__t.u64()),
});
export type WorldCharacterRow = __Infer<typeof WorldCharacterRow>;

export const WorldPackage = __t.object("WorldPackage", {
  packageId: __t.string(),
  ownerPrincipalId: __t.string(),
  slug: __t.string(),
  displayName: __t.string(),
  manifestJson: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type WorldPackage = __Infer<typeof WorldPackage>;

export const WorldPatch = __t.object("WorldPatch", {
  patchId: __t.string(),
  packageId: __t.option(__t.string()),
  worldId: __t.option(__t.string()),
  patchKind: __t.string(),
  payloadJson: __t.string(),
  createdAt: __t.u64(),
});
export type WorldPatch = __Infer<typeof WorldPatch>;

export const WorldRelease = __t.object("WorldRelease", {
  releaseId: __t.string(),
  packageId: __t.string(),
  worldId: __t.string(),
  imageRef: __t.string(),
  revision: __t.string(),
  configJson: __t.string(),
  createdAt: __t.u64(),
  deployedAt: __t.option(__t.u64()),
});
export type WorldRelease = __Infer<typeof WorldRelease>;

