// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  worldCharacterId: __t.string(),
  worldId: __t.string(),
  principalId: __t.string(),
  displayName: __t.string(),
  saveKey: __t.option(__t.string()),
  branchKind: __t.option(__t.string()),
  createdAt: __t.u64(),
  lastSeenAt: __t.option(__t.u64()),
};
