// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  username: __t.string(),
  principalId: __t.string(),
  authMode: __t.string(),
  passwordHash: __t.option(__t.string()),
  passwordSalt: __t.option(__t.string()),
  passwordAlgorithm: __t.option(__t.string()),
  externalSubject: __t.option(__t.string()),
  banned: __t.bool(),
  banReason: __t.option(__t.string()),
  createdAt: __t.u64(),
  lastLoginAt: __t.option(__t.u64()),
};
