// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  patchId: __t.string().primaryKey().name("patch_id"),
  packageId: __t.option(__t.string()).name("package_id"),
  worldId: __t.option(__t.string()).name("world_id"),
  patchKind: __t.string().name("patch_kind"),
  payloadJson: __t.string().name("payload_json"),
  createdAt: __t.u64().name("created_at"),
});
