// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  worldId: __t.string().primaryKey().name("world_id"),
  name: __t.string(),
  gamemodeId: __t.string().name("gamemode_id"),
  status: __t.string(),
  releaseId: __t.option(__t.string()).name("release_id"),
  ownerPrincipalId: __t.option(__t.string()).name("owner_principal_id"),
  metadataJson: __t.option(__t.string()).name("metadata_json"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
