// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  worldCharacterId: __t.string().primaryKey().name("world_character_id"),
  worldId: __t.string().name("world_id"),
  principalId: __t.string().name("principal_id"),
  displayName: __t.string().name("display_name"),
  saveKey: __t.option(__t.string()).name("save_key"),
  branchKind: __t.option(__t.string()).name("branch_kind"),
  createdAt: __t.u64().name("created_at"),
  lastSeenAt: __t.option(__t.u64()).name("last_seen_at"),
});
