// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  releaseId: __t.string().primaryKey().name("release_id"),
  packageId: __t.string().name("package_id"),
  worldId: __t.string().name("world_id"),
  imageRef: __t.string().name("image_ref"),
  revision: __t.string(),
  configJson: __t.string().name("config_json"),
  createdAt: __t.u64().name("created_at"),
  deployedAt: __t.option(__t.u64()).name("deployed_at"),
});
